<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_news']['customelement_selection'] 	= array('Mein Inhaltselement wählen','Wählen Sie hier eins Ihrer eigenen Inhaltselemente aus.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_news']['customelement_legend']		= 'Mein Inhaltselement-Einstellungen';